// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsYQRldy_salJ2R4CA4XeCl-gWhwcEsJ8',
    appId: '1:83664425657:web:8d39e504270a46105f4168',
    messagingSenderId: '83664425657',
    projectId: 'chattingapp-39d1d',
    authDomain: 'chattingapp-39d1d.firebaseapp.com',
    storageBucket: 'chattingapp-39d1d.firebasestorage.app',
    measurementId: 'G-0JSVWXE51S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARF1sjDhbz8dqLiqfm-oVGgQk44Bs7Rbo',
    appId: '1:83664425657:android:c2bfad9efae0859e5f4168',
    messagingSenderId: '83664425657',
    projectId: 'chattingapp-39d1d',
    storageBucket: 'chattingapp-39d1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARIsxcvoQGEj8MaLs1e9VqbkKIzsixJp8',
    appId: '1:83664425657:ios:814b4e6698ab120c5f4168',
    messagingSenderId: '83664425657',
    projectId: 'chattingapp-39d1d',
    storageBucket: 'chattingapp-39d1d.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARIsxcvoQGEj8MaLs1e9VqbkKIzsixJp8',
    appId: '1:83664425657:ios:814b4e6698ab120c5f4168',
    messagingSenderId: '83664425657',
    projectId: 'chattingapp-39d1d',
    storageBucket: 'chattingapp-39d1d.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsYQRldy_salJ2R4CA4XeCl-gWhwcEsJ8',
    appId: '1:83664425657:web:91fc1401ac02095c5f4168',
    messagingSenderId: '83664425657',
    projectId: 'chattingapp-39d1d',
    authDomain: 'chattingapp-39d1d.firebaseapp.com',
    storageBucket: 'chattingapp-39d1d.firebasestorage.app',
    measurementId: 'G-Q5SSKQD4Z5',
  );
}
